### ISSUE TITLE
[Undesired Behaviour] Writing the letter 'n' in private chats opens the New Post window 

### ISSUE THREAD

**Issue by CelsiusVi** [spuithori/tokimekibluesky#103]
As per the title, when in a private chat textbox, writing the lowercase n in any word opens the New Post tab under the chat layout and changes focus to the New Post textbox, which is also hidden behind the floating chat window.

Key shortcuts should be disabled when writing in chats. A "change/disable keyboard shortcuts" option would be positive too.

**Comment by spuithori** [comment]
This has been fixed and will be closed.
