### ISSUE TITLE
Suggestion: Add an option to increase the image size

### ISSUE THREAD

**Issue by onmyouji** [spuithori/tokimekibluesky#20]
Hello,

Is it possible to add an option to increase the image size?

I think the current image size on tokimeki website is too small.

For comparison:

bluesky website - staging.bsky.app

![2023-04-25_092353](https://user-images.githubusercontent.com/8424198/234159787-9afc3503-9197-4674-a8a6-1212a90e6536.png)

tokimekibluesky

![2023-04-25_092500](https://user-images.githubusercontent.com/8424198/234159844-75762e6f-562f-4042-8373-447788681431.png)

**Comment by spuithori** [comment]
Added options for image size.
