### ISSUE TITLE
image's attached post is no menu

### ISSUE THREAD

**Issue by kappaseijin** [spuithori/tokimekibluesky#3]
<img width="240" alt="images-attached-post" src="https://user-images.githubusercontent.com/1396903/224688231-da88f55c-afbe-4891-8ce3-3904aa7cca30.png">

Title and screen shot.
I use it all the time. Thanks.
Best regards.

**Comment by kappaseijin** [comment]
普段のポストはポストの下にメニューアイコンが表示されてると思います。でも画像添付ポストだけはそれが出ないのでいいねやリポストができないんです。

**Comment by spuithori** [comment]
@kappaseijin 
画像の上にあります。
分かりにくいので順番変えた方が良いかもしれませんね。

**Comment by kappaseijin** [comment]
ほんとだー。失礼しました。
自分が気づかなかっただけなので他の人は普通に使えていたんですね。

ちなみに今公式アプリとtwitterを確認したら下にありました。
縦長画像や複数枚の画像がある時だと下にある方が便利だからそうなっているのかも。

**Comment by kappaseijin** [comment]
@spuithori 
ほんとだー。失礼しました。
自分が気づかなかっただけなので他の人は普通に使えていたんですね。

ちなみに今公式アプリとtwitterを確認したら下にありました。
縦長画像や複数枚の画像がある時だと下にある方が便利だからそうなっているのかも。

**Comment by spuithori** [comment]
デザインを見直し、リアクションボタン類を画像の下部に移動しました。
