### ISSUE TITLE
Tokimeki locks up when a thread starting with a deleted post is open

### ISSUE THREAD

**Issue by Viktini** [spuithori/tokimekibluesky#42]
**Steps to reproduce**
1. Try to open a post on the timeline that was deleted but is stuck on the timeline.
2. It locks up, can't close it.
3. Refresh, Tokimeki locks up entirely.

This is on Pulse Browser 1.0.0-a77 alpha, which is forked from a recent version of Mozilla Firefox if testing is needed.

**Comment by spuithori** [comment]
Thank you for your feedback!
Perhaps it has been fixed.

**Comment by Viktini** [comment]
Seems like it has! Thank you!
