### ISSUE TITLE
Post composer closes when clicking on alt-text window

### ISSUE THREAD

**Issue by Viktini** [spuithori/tokimekibluesky#45]
**Steps to reproduce:**

1. Activate the post composer
2. Upload an image.
3. Click "Enter alt text in the image" to access the alt-text window
4. Click anywhere on the alt-text window

**Intended behaviour**
Clicking anywhere on the alt-text window should not close the post composer.

**Actual behaviour**
The post composer closes.

**Comment by spuithori** [comment]
Thank you for your feedback!
I fix it!
