### ISSUE TITLE
Issue with the "back to top" shortcut while auto scroll is ON

### ISSUE THREAD

**Issue by popopoplus** [spuithori/tokimekibluesky#46]
While using the DECK mode and if auto-scroll is active for a column, clicking on the column's name no longer get you back to the top of your feed.

edit : 
In relation to the auto scroll feature : As things stand, auto-scroll resumes when you click on an image to display it full-screen, so I think it would be a good idea to freeze the column while an image is displayed. Thanks a lot.

edit 2 : 
Regarding the auto-scroll again : If both auto refresh and auto scroll are enabled for a column, auto scroll will be triggered the moment the column automatically refreshes, even if the mouse is inside the column. To cancel auto-scrolling, you need to take the mouse out of the column and put it back in.

**Comment by spuithori** [comment]
@popopoplus 
The subject and edit 1 have been fixed! Edit 2 is under consideration.
