### ISSUE TITLE
New Decks UI breaks some elements

### ISSUE THREAD

**Issue by xenianth** [spuithori/tokimekibluesky#49]
New deck UI has several sections that overlap each other or break entirely once activated:

When in Decks layout, I am unable to scroll through all of my columns (currently have 6) as the scrollbar stops partway through.

If I click a column's icon from the sidebar to navigate to it, the entire window gets a second horizontal scroll bar at the bottom, above the main window one. At the same time, a new header UI appears, which overlaps the decks themselves at the top.

https://github.com/spuithori/tokimekibluesky/assets/108703223/97babe38-f5a8-4f9d-9f4f-64fb0dbc2cba

**Comment by spuithori** [comment]
@xenianth
I think I have probably fixed the problem, but the problem may continue in some environments due to different scroll bar specifications on different operating systems. Please check!

**Comment by xenianth** [comment]
everything is working properly again, thank you!
