### ISSUE TITLE
Repost functionality broken since September 22

### ISSUE THREAD

**Issue by xenianth** [spuithori/tokimekibluesky#59]
Trying to repost any post causes entire page to dim and become unresponsive. Requires page reload to gain site response again. Have to copy url of each post to open in official site to be able to repost. Quote-reposting works with no issue.

Firefox 117.0.1

**Comment by spuithori** [comment]
@xenianth 
Sorry, I added a confirmation dialog when reposting and deleting, but the display was broken in Firefox.
Fixed. Thanks for the feedback!

**Comment by xenianth** [comment]
thanks for the quick fix!
