### ISSUE TITLE
An unnecessary blank space exists on smartphone view

### ISSUE THREAD

**Issue by oboenikui** [spuithori/tokimekibluesky#64]
## Description

When used in smartphone view, there is an extra margin at the bottom. If you press the top tab, the whole body will rise up, making it difficult to push other tabs. Also, when you swipe up on the bottom navigation, it will rise up even higher.

![](https://github.com/spuithori/tokimekibluesky/assets/3191462/109b91a1-7766-43b0-b88b-ceb589aab943)

## Problems

- You won't be able to press the top tabs.
- The bottom extra margin is displayed.
- Sometimes the reaction position of the touch may shift above the display position (this may have nothing to do with this problem).

## Expected behavior

- The tab will continue to be displayed even after pressing the tab
- Even if you swipe up on the bottom navigation, the whole body will not rise up.

## Environment

- OS: iOS 17.1.1
- Device: iPhone 15 Pro Max
- Browser: Safari (can reproduce both in browser mode and in PWA mode)

**Comment by oboenikui** [comment]
It seems to have already been fixed. Thank you for fixing!

**Comment by spuithori** [comment]
@oboenikui 
Thank you!
I think this problem has been fixed , but please check back.

**Comment by oboenikui** [comment]
@spuithori 
> Sometimes the reaction position of the touch may shift above the display position (this may have nothing to do with this problem).
I don't know the conditions under which this problem occurs, so I will report issue again if it recurs.
I have been using the fixed version for about a day and have not occured the same problem.
