### ISSUE TITLE
Please provide option to hide huge "Atmosphere" field from profiles

### ISSUE THREAD

**Issue by xenianth** [spuithori/tokimekibluesky#86]
This was added in the past few days I think, and there is no documentation or mention of it in any update notes. Can we please have an option to disable it? It horribly formats the actual profile bio itself and is empty in just about every profile I view anyway. It breaks the line for following numbers on larger accounts, as well as breaking the line for the toggle to show/hide following number. On many accounts it is so tall and squished that the profile bio alone takes up almost the whole height of my screen. I will not be using the feature as it's not relevant to my needs, and the service itself that provides the link menu (Linkat) requires our actual Bluesky password and not an App Password, so it is not a secure method of link sharing anyway.

![Screenshot 2024-10-10 134431](https://github.com/user-attachments/assets/3ec5340b-734e-49e4-95d4-2ecb90a116b3)
![Screenshot 2024-10-10 134528](https://github.com/user-attachments/assets/bf927ab0-a948-4dcb-8c60-0ce0025ea8d3)
![Screenshot 2024-10-10 134637](https://github.com/user-attachments/assets/91dc3f82-4366-4f56-b4f3-16588275b82e)

**Comment by spuithori** [comment]
@xenianth 
Hi!
This feature can be hidden from the “Hide Atmosphere profile” in the Settings->General menu.

**Comment by xenianth** [comment]
thank you, it works!
